### ISSUE TITLE
500 Server Error in Meta Resource

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#56]
When spec extraction is enabled, the `/meta` resource responds with a 500 error.

The stack trace in the error is:

```
createFile must be a function
    at Error (native)
    at Object.extractSpecs (/lynx-docs/src/lib/export/lynx/extract-specs.js:14:44)
    at processTemplate (/lynx-docs/src/lib/export/process-template.js:56:27)
    at transformVariantToLynx (/lynx-docs/src/lib/export/variants-to-lynx.js:34:20)
    at serveVariant (/lynx-docs/src/server/meta/serve-meta.js:21:17)
    at /lynx-docs/src/server/meta/serve-meta.js:45:5
    at /lynx-docs/src/server/index.js:34:5
    at /lynx-docs/src/server/index.js:35:7
    at /lynx-docs/src/server/serve-cors.js:8:42
    at /lynx-docs/src/server/index.js:34:5
```

**Comment by ansongoldade** [comment]
I disabled spec extraction for meta resources. If you agree with that approach to resolving this issue, please review the changes and close the issue.
